# Run tests with: uv run pytest; uv run ty check; uv run pyright; uv run ruff check; uv run ruff format --diff

# Project configuration
[project]
name = "py-ham-bbs"
version = "0.1.0"
description = "Python based BBS"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "websockets",
    "uuid6; python_version < '3.14'",
]

# Install with uv sync --upgrade --all-groups
[dependency-groups]
dev = ["pyright", "ty", "pytest", "ruff"]

# Install with uv sync --upgrade --extra=uuid
[project.optional-dependencies]
uuid = ["uuid6"]

[tool.pytest.ini_options]
minversion = "9.0"
addopts = ["-ra", "--strict-config", "-v"]
testpaths = ["tests"]
python_files = ["test_*.py"]
filterwarnings = ["always"]
pythonpath = ["src"]

[tool.ty.rules]
possibly-missing-attribute = "warn"
possibly-missing-import = "warn"
possibly-unresolved-reference = "warn"

[tool.ty.environment]
root = ["src", "src/lib"]

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = true
reportUnusedImport = "error"
reportUnusedVariable = "error"
reportPrivateUsage = "error"
reportIncompatibleMethodOverride = "error"
reportIncompatibleVariableOverride = "error"
reportUntypedFunctionDecorator = "error"

[[tool.pyright.executionEnvironments]]
root = "."
extraPaths = ["src", "src/lib", ".venv/lib/python3.14/site-packages", ".venv/lib/python3.13/site-packages"]

[tool.ruff]
target-version = "py314"
line-length = 320

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	"D",      # all docstring rules
	"T20",    # print() rules
	"TC003",  # all std imports without typecheck
	"FBT",    # boolean trap rules
	"PLR",    # magic values, too many returns, etc.
	"TRY",    # exception message rules
	"EM",     # exception literal rules
	"B028",   # warnings stacklevel
	"I001",   # import block formatting
	"INP",    # implicit namespace package
	"S101",   # assert in tests
	"C90",    # complexity rules
	"W191",   # allow tabs for indentation
	"ERA",    # allow commented-out code
	"E501",   # allow long lines
	"COM812", # avoid formatter conflict warnings
	"TC006",  # ignore unquoted type expressions in typing.cast() calls
	"TD002",  # author in TODO
	"TD003",  # issue link in TODO
	"RUF023", # allow unsorted dunder methods 
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
line-ending = "lf"
